sudo: false

branches:
  only:
    - publicGithubDevelop

script:
  - wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz --no-check-certificate
  - tar -zxvf download
  - ./doxygen-1.9.2/bin/doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: publicGithubDevelop
